<?php

namespace Partitech\SonataMenu\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
}
