#controllers:
#  resource:
#    path: ../src/Controller/
#    namespace: App\Controller
#  type: attribute
sonata_menu.routes:
  type: annotation
  resource: '../src/Controller'


#admin_route_list:
#  path: /admin/routes
#  controller: App\Controller\Admin\RouteAdminController::listAction
#  methods: GET
